### PR TITLE
Consolidate build system changes

### PR DESCRIPTION
**Pull request by RafaelPalomar**
This PR consolidates the work in `Slicer/SlicerSOFA` in branch `fix/adapt_to_slicer_building_system` and Slicer/SlicerSOFA#14.

In addition, and after discussion with @bakpaul, reached the conclusion that SOFA uses header-only components from boost, so build and installation of boost is not required in this extension. Consequently, this PR includes changes in the build system to avoid building and installing boost.

### CODE REVIEW

**Comment by lassoan** [comment]
The problem is still not solved. Boost still causes the build to fail on Windows ([logs](https://1drv.ms/f/s!Arm_AFxB9yqH0-ofWUxuPG6kRerO0g?e=1THzqH)). So frustrating.

Instead of wasting any more time with this could we vendorize the few header files that are needed from boost? If needed then we could fork SOFA until SOFA developers find the time to get rid of boost. You can extract relevant pieces using [bcp](https://stackoverflow.com/questions/5306745/getting-only-necessary-headers-out-of-boost) and add the .h files to the the SOFA or SlicerSOFA repository.

**Comment by lassoan** [comment]
The errors that I described are from the main branch. I'll try to build this branch and report back.

**Comment by lassoan** [comment]
Good news! This branch was successfully built and packaged on Windows. I've installed the package and it actually worked out of the box! Great job!

https://github.com/user-attachments/assets/fd9344fc-5143-4865-b4fd-eff518935ad8

I've only found one small issue related to building and packaging: There is about 75MB of redundant binaries in the package.
- This folder content is needed:
  - `inner-build\_CPack_Packages\win64\ZIP\33142-win-amd64-SlicerSOFA-git3877ff5-2024-12-07\bin\Release`
- But these folders should not be included in the package:
  - `inner-build\_CPack_Packages\win64\ZIP\33142-win-amd64-SlicerSOFA-git3877ff5-2024-12-07\bin\Debug`
  - `inner-build\_CPack_Packages\win64\ZIP\33142-win-amd64-SlicerSOFA-git3877ff5-2024-12-07\bin\MinSizeRel`
  - `inner-build\_CPack_Packages\win64\ZIP\33142-win-amd64-SlicerSOFA-git3877ff5-2024-12-07\bin\RelWithDebInfo`

**Comment by RafaelPalomar** [comment]
@lassoan, @jcfr, I need a review to be able to merge this. @lassoan, the bug on starting/stopping should be corrected now in `6e0fe07`

**Review by lassoan — APPROVED** [review]
Thank you, this is great!

**Comment by lassoan** [comment]
What was the problem with starting/stopping and how was it fixed?

**Comment by RafaelPalomar** [comment]
> What was the problem with starting/stopping and how was it fixed?

@lassoan, it wasn't really related to starting/stopping the simulation, but on the data transfer from Slicer to SOFA , we were passing by mistake more data than expected by SOFA, generating memory issues. This is the commit solving it: https://github.com/Slicer/SlicerSOFA/pull/28/commits/6e0fe0799623d19c9b42aa848283fc16d043dcca

**Pull request merged**
